"""
Replay buffer for AlphaZero-style training.

Stores training examples from self-play: (state_data, mcts_policy, outcome_value).
Examples are drawn uniformly at random for training, regardless of which game they came from.

The buffer is implemented as a circular (ring) buffer with fixed capacity.
When full, the oldest examples are overwritten first. This naturally biases
training toward examples generated by the most recent version of the network,
which is important because older examples were generated by a weaker policy.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from typing import Optional

import torch
from torch_geometric.data import Data, Batch


@dataclass
class TrainingExample:
    """A single training example from self-play.

    Attributes:
        state_data: PyG Data object (preprocessed) for the state at which MCTS was run.
        mcts_policy: Dict mapping action tuples to visit-count probabilities.
                     This is the target for the policy head.
        value_target: The eventual episode outcome (e.g. normalized T-gate reduction).
                      This is the target for the value head.
                      Set to None during self-play and filled in retroactively.
        game_id: Optional identifier for which self-play game produced this example.
    """
    state_data: Data
    mcts_policy: dict[tuple, float]
    value_target: Optional[float] = None
    game_id: Optional[int] = None


class ReplayBuffer:
    """Circular replay buffer for self-play training examples.

    The buffer stores TrainingExample objects and supports:
    - Adding single examples or entire games (lists of examples)
    - Uniform random sampling of minibatches
    - Automatic eviction of the oldest examples when capacity is reached

    The capacity is measured in individual examples, not games. This means
    a single game's examples may be partially evicted (some steps retained,
    others overwritten). This is intentional — it provides a natural
    curriculum where recent experience dominates.
    """

    def __init__(self, capacity: int = 100_000):
        """
        :param capacity: Maximum number of training examples to store.
                         When exceeded, oldest examples are overwritten.
        """
        self.capacity = capacity
        self._buffer: list[Optional[TrainingExample]] = [None] * capacity
        self._write_idx: int = 0
        self._size: int = 0
        self._total_added: int = 0  # Lifetime count for stats

    def add(self, example: TrainingExample) -> None:
        """Add a single training example to the buffer."""
        self._buffer[self._write_idx] = example
        self._write_idx = (self._write_idx + 1) % self.capacity
        self._size = min(self._size + 1, self.capacity)
        self._total_added += 1

    def add_game(self, examples: list[TrainingExample]) -> None:
        """Add all training examples from a single self-play game."""
        for example in examples:
            self.add(example)

    def sample(self, batch_size: int) -> list[TrainingExample]:
        """Sample a minibatch of training examples uniformly at random.

        :param batch_size: Number of examples to sample. Clamped to buffer size.
        :return: List of TrainingExample objects.
        :raises ValueError: If the buffer is empty.
        """
        if self._size == 0:
            raise ValueError("Cannot sample from an empty replay buffer")
        actual_batch_size = min(batch_size, self._size)
        indices = random.sample(range(self._size), actual_batch_size)
        return [self._buffer[i] for i in indices]

    def __len__(self) -> int:
        return self._size

    @property
    def total_added(self) -> int:
        """Total number of examples ever added (including overwritten ones)."""
        return self._total_added

    @property
    def is_full(self) -> bool:
        return self._size >= self.capacity


def collate_training_batch(
    examples: list[TrainingExample],
    device: torch.device = torch.device('cpu'),
) -> tuple[Batch, torch.Tensor, torch.Tensor]:
    """Collate a list of TrainingExamples into tensors suitable for training.

    The policy target is tricky because each example has a different set of actions
    in its MCTS policy dict. We don't need to reconstruct the full action distribution —
    instead, we'll compute the policy loss per-example in the training loop by running
    the model's distribution.log_prob() on the MCTS-selected actions.

    However, for the value target, we simply stack scalars.

    For the state data, we use PyG's Batch to combine variable-size graphs.

    :param examples: List of TrainingExample objects with value_target set.
    :param device: Device to move tensors to.
    :return: (batched_data, policy_targets, value_targets)
             - batched_data: PyG Batch of graph data
             - policy_targets: List of policy dicts (can't be tensorized due to variable actions)
             - value_targets: Tensor of shape (batch_size,) with outcome values
    """
    data_list = [ex.state_data for ex in examples]
    batch = Batch.from_data_list(data_list).to(device)

    value_targets = torch.tensor(
        [ex.value_target for ex in examples],
        dtype=torch.float32,
        device=device,
    )

    # Policy targets stay as dicts — the training loop handles them per-example
    policy_targets = [ex.mcts_policy for ex in examples]

    return batch, policy_targets, value_targets
